name: Export ERPNext Images
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull images
        run: |
          docker pull redis:8.6-alpine
          docker pull mariadb:10.11
          docker pull frappe/frappe:version-15
          docker pull frappe/erpnext:v15.48.0

      - name: Save to tar
        run: |
          docker save redis:8.6-alpine -o redis_8.6-alpine.tar
          docker save mariadb:10.11 -o mariadb_10.11.tar
          docker save frappe/frappe:version-15 -o frappe_version-15.tar
          docker save frappe/erpnext:v15.48.0 -o erpnext_v15.48.0.tar

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          files: "*.tar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}