name: Export ERPNext Images
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 安装导出工具
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: 流式导出镜像为tar
        run: |
          skopeo copy docker://redis:8.6-alpine docker-archive:redis_8.6-alpine.tar
          skopeo copy docker://mariadb:10.11 docker-archive:mariadb_10.11.tar
          skopeo copy docker://frappe/erpnext:v15.48.0 docker-archive:erpnext_v15.48.0.tar

      - name: 发布到Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.3
          files: "*.tar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
